### ISSUE TITLE
Failed to pull v1.6.0 images on OCP 4.7 environment

### ISSUE THREAD

**Issue by lbscorpio** [IBM/ibm-block-csi-driver#332]
Hi team,

On OCP 4.7 environment, I can see that OLM have upgraded the operator to v1.6.0, but the related PODs failed to be running due to ImagePullBackOff.
```
# date; oc -n ibm-block-csi get pod
Thu Jun 10 09:51:55 CST 2021
NAME                                     READY   STATUS             RESTARTS   AGE
ibm-block-csi-controller-0               5/6     ImagePullBackOff   0          26m
ibm-block-csi-node-cdtfk                 2/3     ImagePullBackOff   0          26m
ibm-block-csi-node-dgsth                 2/3     ImagePullBackOff   0          48m
ibm-block-csi-node-qrwfs                 3/3     Running            0          3d1h
ibm-block-csi-operator-c66f65b5c-bvj6f   1/1     Running            0          10h
```
Some details events as below:
```
  Normal   Pulling         27m (x2 over 28m)     kubelet            Pulling image "ibmcom/ibm-block-csi-driver-controller:1.6.0"
  Warning  Failed          27m (x2 over 28m)     kubelet            Error: ErrImagePull
  Warning  Failed          27m (x2 over 28m)     kubelet            Failed to pull image "ibmcom/ibm-block-csi-driver-controller:1.6.0": rpc error: code = Unknown desc = Error reading manifest 1.6.0 in docker.io/ibmcom/ibm-block-csi-driver-controller: manifest unknown: manifest unknown
  Warning  Failed          13m (x62 over 28m)    kubelet            Error: ImagePullBackOff
  Normal   BackOff         3m3s (x105 over 28m)  kubelet            Back-off pulling image "ibmcom/ibm-block-csi-driver-controller:1.6.0"

  Normal   Pulling    49m (x3 over 51m)    kubelet            Pulling image "ibmcom/ibm-block-csi-driver-node:1.6.0"
  Warning  Failed     49m (x3 over 50m)    kubelet            Failed to pull image "ibmcom/ibm-block-csi-driver-node:1.6.0": rpc error: code = Unknown desc = Error reading manifest 1.6.0 in docker.io/ibmcom/ibm-block-csi-driver-node: manifest unknown: manifest unknown
  Warning  Failed     49m (x3 over 50m)    kubelet            Error: ErrImagePull
  Warning  Failed     10m (x168 over 50m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    45s (x210 over 50m)  kubelet            Back-off pulling image "ibmcom/ibm-block-csi-driver-node:1.6.0"
```
I think the new release images didn't upload to the dockerhub `docker.io/ibmcom`. Could you help to fix it soon? Thanks.

Best Regards,
Bob

**Comment by roysahar-ibm** [comment]
@lbscorpio,
Sorry on this, we had a faulty push of release candidate (OCP 4.7 pointed to latest image not version), the issue has been fixed 1 hour later and the latest images are back to be 1.5.0.
In order to fix your situation you will need to uninstall the driver CR and operator and than install the operator (should be 1.5.0).
Sorry for the inconvenience.

**Comment by lbscorpio** [comment]
@roysahar-ibm Thanks for your update, I have used a workaround to use 1.5.0 only. You can close this issue if have fixed it, thanks.

**Comment by roysahar-ibm** [comment]
@lbscorpio Thanks for the update - closing the issue.

**Comment by lbscorpio** [comment]
@roysahar-ibm Seems that the issue was not fixed, I tried v1.6.0 again today and found different errors, have you tested on OCP 4.7 environment? Thanks.
```
  Normal   Pulling         5m58s (x2 over 7m59s)  kubelet            Pulling image "ibmcom/ibm-block-csi-driver-controller:1.6.0"
  Warning  Failed          3m12s                  kubelet            Failed to pull image "ibmcom/ibm-block-csi-driver-controller:1.6.0": rpc error: code = Unknown desc = Error reading blob sha256:d0c9851d609d0bfab8ea16ae528b7ace74e6856bf9215f644ec611974aa5019e: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/d0/d0c9851d609d0bfab8ea16ae528b7ace74e6856bf9215f644ec611974aa5019e/data?verify=1624946829-zsaCwSfrQ3MwxdOqbo4YtmM%2F03w%3D": dial tcp 104.18.125.25:443: i/o timeout

  Warning  Failed     5m7s                   kubelet            Failed to pull image "ibmcom/ibm-block-csi-driver-node:1.6.0": rpc error: code = Unknown desc = Error parsing image configuration: Get "https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/85/850a032ab59c3ee7c37b13de63fbae2e6265f02fcd0516a6ede0d00df4505ec3/data?verify=1624946801-j1%2BNiEmat6LeLZGvXSZQPVsQM70%3D": dial tcp 104.18.125.25:443: i/o timeout
  Warning  Failed     2m29s (x3 over 7m18s)  kubelet            Error: ErrImagePull
```
